server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/animal_husbandry
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=awb

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

security.jwt.secret-key=22A2695EDDA4A9F6EC8174A3A143517FB4B2A5AF373565856A6AD14B3637D813
security.jwt.issuer=springsecurity jwt API