spring.application.name=springSecurity
#spring.datasource.url=jdbc:postgresql://localhost:5432/dhanwanthari-dev

spring.datasource.url=jdbc:postgresql://localhost:5432/masterdb
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


server.port = 8888

security.jwt.secret-key = 22A2695EDDA4A9F6EC8174A3A143517FB4B2A5AF373565856A6AD14B3637D813
security.jwt.issuer = springsecurity jwt API
